### ISSUE TITLE
Author affiliation 1 char short if only in DBLP and with comma

### ISSUE THREAD

**Issue by noleti** [HexHive/pubstats#1]
I saw a bunch of affiliations with incomplete affiliation strings. Random example: Ulrich Rührmair

It looks to me that this is due to affiliations from DBLP used, as for that example no csrankings affiliation is present. 

Likely cause: off-by one error in 
https://github.com/HexHive/pubstats/blob/a01d64a17e0f7f6ed608a74c4d5d0f48e8008f90/parse_dblp.py#L72

should likely be `author_affiliation = author_affiliation[0:author_affiliation.find(',')]`

In this specific scenario, I would actually question if cutting the ", Germany" part makes much sense. I guess the intention was to limit affiliations to one.

**Comment by gannimo** [comment]
Looks like we discovered the same bug at the same time. Fixed concurrently in 9c22ce6d4eaf519a1815e3ea3bf2d7fd5569d982. Thanks for bringing this up. Handling affiliations is a bit of a pain as both CSrankings and DBLP are incomplete and use slightly different styles and conventions.
