### ISSUE TITLE
Website is not available for safari web browser

### ISSUE THREAD

**Issue by louismerlin** [HexHive/pubstats#2]
After sending the website to @hugoroussel, he replied with this screenshot :

![image](https://user-images.githubusercontent.com/12018334/104125776-49c87200-5359-11eb-8b97-fe44f3ae80b8.png)

From what I could gather, this is an encoding issue, the server says that encoding is `gzip, gzip`, which seems to break safari (see [here](https://serverfault.com/questions/710185/safari-does-not-decompress-gzip-content-when-content-encoding-is-gzip-gzip)). Or maybe a different but similar encoding bug ?

The project is great by the way, very interesting to browse through the different sections !

**Comment by gannimo** [comment]
Thanks for letting me know, this seems to be an Apache2 (mod_headers)/Safari conflict. I've adjusted the configuration and added gzip content encoding. Can you test again?

**Comment by louismerlin** [comment]
Works on my iPhone 👍
